// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNJijlqj4C7cBftgOw8sngiHwLQBdHjQ',
    appId: '1:1044204614703:web:c7efcc5b1ab73f74d6c2da',
    messagingSenderId: '1044204614703',
    projectId: 'vi-vote',
    authDomain: 'vi-vote.firebaseapp.com',
    storageBucket: 'vi-vote.appspot.com',
    measurementId: 'G-W1106998P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZOpEm_LZ5NrS10UQIC_Oxp1OwBN2LcZ4',
    appId: '1:1044204614703:android:cacf3b2188f4311ed6c2da',
    messagingSenderId: '1044204614703',
    projectId: 'vi-vote',
    storageBucket: 'vi-vote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjYzjGOACj-b5E9W4B7NaRGYk262dO-MA',
    appId: '1:1044204614703:ios:dc18a99af0e80610d6c2da',
    messagingSenderId: '1044204614703',
    projectId: 'vi-vote',
    storageBucket: 'vi-vote.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjYzjGOACj-b5E9W4B7NaRGYk262dO-MA',
    appId: '1:1044204614703:ios:23a03dbdcfc7ab7ad6c2da',
    messagingSenderId: '1044204614703',
    projectId: 'vi-vote',
    storageBucket: 'vi-vote.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
